version: '3.4'

services:
  shopping.api:
    image: templateapi.azurecr.io/shoppingapi #${DOCKER_REGISTRY-}shoppingapi 
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shopping.client:
    image: templateapi.azurecr.io/shoppingclient #${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.db:
    image: templateapi.azurecr.io/mongo #mongo